onlyBuiltDependencies:
  - core-js
  - core-js-pure

overrides:
  '@docusaurus/core': 3.9.2
  '@docusaurus/theme-common': 3.9.2
  '@docusaurus/plugin-content-docs': 3.9.2
  '@docusaurus/plugin-content-blog': 3.9.2
  '@docusaurus/bundler': 3.9.2
  webpack: 5.97.0
