import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  agents: [
    {type: 'autogenerated', dirName: 'agents/python'},
    {type: 'link', label: '数据库 ⤴', href: '/common/database/'},
  ],
  backend: [],
  devops: [],
  'ai-coding': [],
  fullstack: [],
  career: [],
  common: [{type: 'autogenerated', dirName: 'common'}],
};

export default sidebars;
